#!/usr/bin/env bash
# This script installs and configures Nginx to serve a "Hello World!" page on Ubuntu

# Update package list and install Nginx
apt-get update -y
apt-get install nginx -y
sudo ufw allow 'Nginx HTTP'
# Create a custom index.html file with "Hello World!"
sh -c 'echo "Hello World!" > /var/www/html/index.html'

# Start Nginx service (using service command instead of systemctl)
service nginx restart
