#!/usr/bin/env bash
# This script installs and configures Nginx to serve a "Hello World!" page on Ubuntu

# Update package list and install Nginx
apt-get update -y
apt-get install nginx -y
sudo ufw allow 'Nginx HTTP'
# Create a custom index.html file with "Hello World!"
sh -c 'echo "Hello World!" > /var/www/html/index.html'
sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/@cryptotechcoder permanent;' /etc/nginx/sites-available/default
# Start Nginx service (using service command instead of systemctl)
service nginx restart
