#!/usr/bin/env bash
# sets up a new 404 error page
sudo apt-get update -y
sudo apt-get install -y nginx 
sudo ufw allow 'Nginx HTTP'
sh -c 'echo "Hello World!" >/var/www/html/index.html'
sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/@cryptotechcoder permanent;' /etc/nginx/sites-available/default
sed -i '/listen 80 default_server/a error_page 404 /404.html;' /etc/nginx/sites-available/default
service nginx restart
